USE [ocb_platform];
GO

/*========================================================================================================================*

    OCB PLATFORM v1.0.0

    SILVER SOURCE-LAYER TABLE DEPLOYMENT

    Purpose:
        Establish the Silver layer for the frozen synthetic source dataset,
        controlled reference data, provenance, and OCB-wide customer identity
        resolution.

    Architecture:

        FROZEN GENERATOR OUTPUT
                    ↓
                 BRONZE
                    ↓
                 SILVER
                    ↓
                  GOLD
                    ↓
              INTELLIGENCE


    SILVER PRINCIPLE:

        Silver preserves source-world evidence while applying controlled
        standardisation, identity resolution, and analytical conformance.


    SILVER CONFORMANCE:

        Native source identifiers are preserved.

        ocb_customer_id is the canonical OCB-wide surrogate customer identity.

        ocb_customer_id is generated by the approved Silver identity-resolution
        process from the Bronze source customer records.

        ocb_customer_identity maps each source-system customer identity to its
        resolved OCB customer identity.

        ocb_customer_id replaces the previously proposed ocb_customer_key.

        ocb_customer_key does not exist in the redesigned Silver layer.


    SILVER CONTAINS:

        PROVENANCE
            load_batch

        REFERENCE DATA
            ref_transaction_type
            ref_transaction_status
            ref_transaction_channel
            ref_currency
            ref_country

        OCB CUSTOMER RESOLUTION
            ocb_customer
            ocb_customer_identity

        ANANSE
            ananse_customer
            ananse_wallet
            ananse_transaction

        SIKACREDIT
            sikacredit_customer
            sikacredit_loan
            sikacredit_repayment

        OMAN REMIT
            oman_remit_customer
            oman_remit_remittance


    OCB CUSTOMER IDENTITY MODEL:

        source_entity
        source_customer_id
                ↓
        ocb_customer_id


    IMPORTANT:

        - Native source identifiers are retained.
        - ocb_customer_id is the canonical OCB surrogate customer identity.
        - ocb_customer_key is not created.
        - Source customer records are not deleted after identity resolution.
        - flag = 1 identifies the canonical source record used to populate
          ocb_customer attributes.
        - flag > 1 remains valid source identity evidence and is retained in
          ocb_customer_identity.
        - Source-specific attributes remain unchanged.
        - No Gold tables are created here.
        - No analytical/business rules are applied here.
        - Reference tables retain their Silver ref_* naming.


    EXPECTED SILVER TABLES:

        16 total

        1   load_batch
        5   reference
        2   OCB customer resolution
        3   Ananse
        3   SikaCredit
        2   Oman Remit


*========================================================================================================================*/
/*========================================================================================================================*

    1. CREATE SILVER SCHEMA

*========================================================================================================================*/
IF NOT EXISTS (
        SELECT
            1
        FROM sys.schemas
        WHERE name = N'silver'
        )
BEGIN
    PRINT '>> silver schema not found. Creating...';

    EXEC ('CREATE SCHEMA [silver]');

    PRINT '>> silver schema created successfully.';
END
ELSE
BEGIN
    PRINT '>> silver schema already exists. No action required.';
END;
GO

/*========================================================================================================================*

    2. DROP EXISTING SILVER TABLES

    Development deployment.

    Tables are dropped in child-to-parent dependency order.

    WARNING:
        Existing Silver data will be permanently deleted.

*========================================================================================================================*/
DROP TABLE IF EXISTS silver.[ananse_transaction];

DROP TABLE IF EXISTS silver.[ananse_wallet];

DROP TABLE IF EXISTS silver.[ananse_customer];

DROP TABLE IF EXISTS silver.[sikacredit_repayment];

DROP TABLE IF EXISTS silver.[sikacredit_loan];

DROP TABLE IF EXISTS silver.[sikacredit_customer];

DROP TABLE IF EXISTS silver.[oman_remit_remittance];

DROP TABLE IF EXISTS silver.[oman_remit_customer];

DROP INDEX IF EXISTS idx_silver_ocb_customer_identity_cross_domain_id ON
        silver.[ocb_customer_identity];

DROP INDEX IF EXISTS idx_silver_ocb_customer_identity_ocb_customer_id ON
        silver.[ocb_customer_identity];

DROP TABLE IF EXISTS silver.[ocb_customer_identity];

DROP TABLE IF EXISTS silver.[ocb_customer];

DROP TABLE IF EXISTS silver.[ref_transaction_channel];

DROP TABLE IF EXISTS silver.[ref_transaction_status];

DROP TABLE IF EXISTS silver.[ref_transaction_type];

DROP TABLE IF EXISTS silver.[ref_currency];

DROP TABLE IF EXISTS silver.[ref_country];

DROP TABLE IF EXISTS silver.[load_batch];

PRINT '>> EXISTING SILVER TABLES DROPPED';
GO

PRINT '===============================================================';
PRINT '>>> SILVER SOURCE-LAYER DEPLOYMENT STARTED <<<';
PRINT '===============================================================';
GO

/*========================================================================================================================*

    3. SILVER LOAD-BATCH PROVENANCE

    One row identifies one source-data load.

    Fields:

        load_id
        source_entity
        source_file_name
        load_timestamp

    The source CSV itself is not modified to contain these fields.

*========================================================================================================================*/
CREATE TABLE silver.[load_batch] (
    load_id          BIGINT IDENTITY(1, 1) NOT NULL,
    source_entity    VARCHAR(100) NOT NULL,
    source_file_name NVARCHAR(255) NOT NULL,
    load_timestamp   DATETIME2(3) NOT NULL
    CONSTRAINT DF_silver_load_batch_load_timestamp
    DEFAULT SYSDATETIME(),
    CONSTRAINT PK_silver_load_batch PRIMARY KEY (load_id)
    );
GO

/*========================================================================================================================*

    4. REFERENCE — TRANSACTION TYPE

*========================================================================================================================*/
CREATE TABLE silver.[ref_transaction_type] (
    transaction_type_id   BIGINT NOT NULL,
    transaction_type_code VARCHAR(20) NOT NULL,
    transaction_type_name VARCHAR(100) NOT NULL,
    CONSTRAINT PK_silver_ref_transaction_type PRIMARY KEY (transaction_type_id)
    );
GO

/*========================================================================================================================*

    5. REFERENCE — TRANSACTION STATUS

*========================================================================================================================*/
CREATE TABLE silver.[ref_transaction_status] (
    transaction_status_id   BIGINT NOT NULL,
    transaction_status_code VARCHAR(20) NOT NULL,
    transaction_status_name VARCHAR(100) NOT NULL,
    CONSTRAINT PK_silver_ref_transaction_status PRIMARY KEY (transaction_status_id)
    );
GO

/*========================================================================================================================*

    6. REFERENCE — TRANSACTION CHANNEL

*========================================================================================================================*/
CREATE TABLE silver.[ref_transaction_channel] (
    transaction_channel_id   BIGINT NOT NULL,
    transaction_channel_code VARCHAR(20) NOT NULL,
    transaction_channel_name VARCHAR(100) NOT NULL,
    CONSTRAINT PK_silver_ref_transaction_channel PRIMARY KEY (transaction_channel_id)
    );
GO

/*========================================================================================================================*

    7. REFERENCE — CURRENCY

*========================================================================================================================*/
CREATE TABLE silver.[ref_currency] (
    currency_id   BIGINT NOT NULL,
    currency_code CHAR(3) NOT NULL,
    currency_name VARCHAR(100) NOT NULL,
    CONSTRAINT PK_silver_ref_currency PRIMARY KEY (currency_id)
    );
GO

/*========================================================================================================================*

    8. REFERENCE — COUNTRY

*========================================================================================================================*/
CREATE TABLE silver.[ref_country] (
    country_id   BIGINT NOT NULL,
    country_code CHAR(3) NOT NULL,
    country_name NVARCHAR(150) NOT NULL,
    CONSTRAINT PK_silver_ref_country PRIMARY KEY (country_id)
    );
GO

/*========================================================================================================================*

    9. OCB CUSTOMER

    Canonical OCB customer registry.

    ocb_customer_id is the OCB-wide surrogate customer identity.

    The canonical attributes are populated from the identity-resolution
    record where flag = 1.

    No ocb_customer_key exists.

*========================================================================================================================*/
CREATE TABLE silver.[ocb_customer] (
    ocb_customer_id BIGINT NOT NULL,
    first_name      NVARCHAR(150) NOT NULL,
    last_name       NVARCHAR(150) NOT NULL,
    date_of_birth   DATE NOT NULL,
    phone_number    VARCHAR(30) NOT NULL,
    email           NVARCHAR(150) NULL,
    CONSTRAINT PK_silver_ocb_customer PRIMARY KEY (ocb_customer_id)
    );
GO

/*========================================================================================================================*

    10. OCB CUSTOMER IDENTITY

    Maps source-system customer identities to the canonical OCB customer.

    One OCB customer may have multiple source-system identities.

    Example:

        OCB_CUSTOMER_ID = 4

            OMAN_REMIT  OR-C000002
            SIKACREDIT  SC-C000002

*========================================================================================================================*/
CREATE TABLE silver.[ocb_customer_identity] (
    source_entity      NVARCHAR(150) NOT NULL,
    source_customer_id VARCHAR(100) NOT NULL,
    cross_domain_id    VARCHAR(100) NOT NULL,
    ocb_customer_id    BIGINT NOT NULL,
    CONSTRAINT PK_silver_ocb_customer_identity PRIMARY KEY (
        source_entity,     
        source_customer_id 
        ),                 
    CONSTRAINT FK_silver_ocb_customer_identity_customer FOREIGN KEY (ocb_customer_id)
    REFERENCES         silver.[ocb_customer](ocb_customer_id)
    );
GO

CREATE INDEX idx_silver_ocb_customer_identity_cross_domain_id ON silver.[ocb_customer_identity] (cross_domain_id);

CREATE INDEX idx_silver_ocb_customer_identity_ocb_customer_id ON silver.[ocb_customer_identity] (ocb_customer_id);
GO

/*========================================================================================================================*

    11. ANANSE CUSTOMER

    Native source customer identity is retained.

    ocb_customer_id provides the resolved OCB-wide customer identity.

*========================================================================================================================*/
CREATE TABLE silver.[ananse_customer] (
    customer_id     VARCHAR(100) NOT NULL,
    ocb_customer_id BIGINT NOT NULL,
    first_name      NVARCHAR(150) NOT NULL,
    last_name       NVARCHAR(150) NOT NULL,
    date_of_birth   DATE NOT NULL,
    nationality     NVARCHAR(150) NOT NULL,
    occupation      NVARCHAR(150) NULL,
    phone_number    VARCHAR(30) NOT NULL,
    email           NVARCHAR(150) NULL,
    created_at      DATETIME2(3) NOT NULL,
    CONSTRAINT PK_silver_ananse_customer PRIMARY KEY (customer_id),
    CONSTRAINT FK_silver_ananse_customer_ocb_customer FOREIGN KEY (ocb_customer_id)
    REFERENCES      silver.[ocb_customer](ocb_customer_id)
    );
GO

/*========================================================================================================================*

    12. SIKACREDIT CUSTOMER

*========================================================================================================================*/
CREATE TABLE silver.[sikacredit_customer] (
    customer_id     VARCHAR(100) NOT NULL,
    ocb_customer_id BIGINT NOT NULL,
    first_name      NVARCHAR(150) NOT NULL,
    last_name       NVARCHAR(150) NOT NULL,
    date_of_birth   DATE NOT NULL,
    nationality     NVARCHAR(150) NOT NULL,
    occupation      NVARCHAR(150) NULL,
    phone_number    VARCHAR(30) NOT NULL,
    email           NVARCHAR(150) NULL,
    created_at      DATETIME2(3) NOT NULL,
    CONSTRAINT PK_silver_sikacredit_customer PRIMARY KEY (customer_id),
    CONSTRAINT FK_silver_sikacredit_customer_ocb_customer FOREIGN KEY (ocb_customer_id)
    REFERENCES      silver.[ocb_customer](ocb_customer_id)
    );
GO

/*========================================================================================================================*

    13. OMAN REMIT CUSTOMER

*========================================================================================================================*/
CREATE TABLE silver.[oman_remit_customer] (
    customer_id     VARCHAR(100) NOT NULL,
    ocb_customer_id BIGINT NOT NULL,
    first_name      NVARCHAR(150) NOT NULL,
    last_name       NVARCHAR(150) NOT NULL,
    date_of_birth   DATE NOT NULL,
    nationality     NVARCHAR(150) NOT NULL,
    occupation      NVARCHAR(150) NULL,
    phone_number    VARCHAR(30) NOT NULL,
    email           NVARCHAR(150) NULL,
    created_at      DATETIME2(3) NOT NULL,
    CONSTRAINT PK_silver_oman_remit_customer PRIMARY KEY (customer_id),
    CONSTRAINT FK_silver_oman_remit_customer_ocb_customer FOREIGN KEY (ocb_customer_id)
    REFERENCES      silver.[ocb_customer](ocb_customer_id)
    );
GO

/*========================================================================================================================*

    14. ANANSE WALLET

    Depends on:

        silver.ananse_customer
        silver.ocb_customer

*========================================================================================================================*/
CREATE TABLE silver.[ananse_wallet] (
    wallet_id       BIGINT NOT NULL,
    customer_id     VARCHAR(100) NOT NULL,
    ocb_customer_id BIGINT NOT NULL,
    CONSTRAINT PK_silver_ananse_wallet PRIMARY KEY (wallet_id),
    CONSTRAINT FK_silver_ananse_wallet_customer FOREIGN KEY (customer_id)
    REFERENCES      silver.[ananse_customer](customer_id),
    CONSTRAINT FK_silver_ananse_wallet_ocb_customer FOREIGN KEY (ocb_customer_id)
    REFERENCES      silver.[ocb_customer](ocb_customer_id)
    );
GO

/*========================================================================================================================*

    15. SIKACREDIT LOAN

*========================================================================================================================*/
CREATE TABLE silver.[sikacredit_loan] (
    loan_id                      VARCHAR(100) NOT NULL,
    customer_id                  VARCHAR(100) NOT NULL,
    ocb_customer_id              BIGINT NOT NULL,
    disbursement_timestamp       DATETIME2(3) NOT NULL,
    disbursement_location_region NVARCHAR(150) NOT NULL,
    disbursement_location_town   NVARCHAR(150) NOT NULL,
    maturity_date                DATE NOT NULL,
    principal_amount             DECIMAL(18, 4) NOT NULL,
    interest_rate                DECIMAL(5, 4) NOT NULL,
    loan_currency                CHAR(3) NOT NULL,
    CONSTRAINT PK_silver_sikacredit_loan PRIMARY KEY (loan_id),
    CONSTRAINT FK_silver_sikacredit_loan_customer FOREIGN KEY (customer_id)
    REFERENCES                   silver.[sikacredit_customer](customer_id),
    CONSTRAINT FK_silver_sikacredit_loan_ocb_customer FOREIGN KEY (ocb_customer_id)
    REFERENCES                   silver.[ocb_customer](ocb_customer_id)
    );
GO

/*========================================================================================================================*

    16. OMAN REMIT REMITTANCE

*========================================================================================================================*/
CREATE TABLE silver.[oman_remit_remittance] (
    remittance_id                  VARCHAR(100) NOT NULL,
    customer_id                    VARCHAR(100) NOT NULL,
    ocb_customer_id                BIGINT NOT NULL,
    remittance_origin_country      NVARCHAR(150) NOT NULL,
    remittance_location_region     NVARCHAR(150) NOT NULL,
    remittance_location_town       NVARCHAR(150) NOT NULL,
    remittance_transaction_channel VARCHAR(100) NOT NULL,
    remittance_type                VARCHAR(100) NOT NULL,
    remittance_status              VARCHAR(100) NOT NULL,
    remittance_timestamp           DATETIME2(3) NOT NULL,
    remittance_amount              DECIMAL(18, 4) NOT NULL,
    remittance_currency            CHAR(3) NOT NULL,
    CONSTRAINT PK_silver_oman_remit_remittance PRIMARY KEY (remittance_id),
    CONSTRAINT FK_silver_oman_remit_remittance_customer FOREIGN KEY (customer_id)
    REFERENCES                     silver.[oman_remit_customer](customer_id),
    CONSTRAINT FK_silver_oman_remit_remittance_ocb_customer FOREIGN KEY (ocb_customer_id)
    REFERENCES                     silver.[ocb_customer](ocb_customer_id)
    );
GO

/*========================================================================================================================*

    17. ANANSE TRANSACTION

    Silver conformance:

        - Native customer_id retained.
        - Native wallet_id retained.
        - Resolved ocb_customer_id propagated.
        - Reference IDs are conformed to descriptive Silver attributes.

*========================================================================================================================*/
CREATE TABLE silver.[ananse_transaction] (
    transaction_id              VARCHAR(100) NOT NULL,
    customer_id                 VARCHAR(100) NOT NULL,
    wallet_id                   BIGINT NOT NULL,
    ocb_customer_id             BIGINT NOT NULL,
    transaction_status          NVARCHAR(150) NOT NULL,
    transaction_type            NVARCHAR(150) NOT NULL,
    transaction_channel         NVARCHAR(150) NOT NULL,
    transaction_currency        NVARCHAR(150) NOT NULL,
    transaction_timestamp       DATETIME2(3) NOT NULL,
    transaction_location_region NVARCHAR(150) NOT NULL,
    transaction_location_town   NVARCHAR(150) NOT NULL,
    device_id                   VARCHAR(100) NOT NULL,
    transaction_amount          DECIMAL(18, 4) NOT NULL,
    CONSTRAINT PK_silver_ananse_transaction PRIMARY KEY (transaction_id),
    CONSTRAINT FK_silver_ananse_transaction_customer FOREIGN KEY (customer_id)
    REFERENCES                  silver.[ananse_customer](customer_id),
    CONSTRAINT FK_silver_ananse_transaction_wallet FOREIGN KEY (wallet_id)
    REFERENCES                  silver.[ananse_wallet](wallet_id),
    CONSTRAINT FK_silver_ananse_transaction_ocb_customer FOREIGN KEY (ocb_customer_id)
    REFERENCES                  silver.[ocb_customer](ocb_customer_id)
    );
GO

/*========================================================================================================================*

    18. SIKACREDIT REPAYMENT

    Customer identity is inherited through loan_id.

    ocb_customer_id is explicitly retained for direct cross-domain analytical
    access without requiring a join through the loan table.

*========================================================================================================================*/
CREATE TABLE silver.[sikacredit_repayment] (
    repayment_id              VARCHAR(100) NOT NULL,
    loan_id                   VARCHAR(100) NOT NULL,
    ocb_customer_id           BIGINT NOT NULL,
    repayment_amount          DECIMAL(18, 4) NOT NULL,
    repayment_timestamp       DATETIME2(3) NOT NULL,
    repayment_location_region NVARCHAR(150) NOT NULL,
    repayment_location_town   NVARCHAR(150) NOT NULL,
    CONSTRAINT PK_silver_sikacredit_repayment PRIMARY KEY (repayment_id),
    CONSTRAINT FK_silver_sikacredit_repayment_loan FOREIGN KEY (loan_id)
    REFERENCES                silver.[sikacredit_loan](loan_id),
    CONSTRAINT FK_silver_sikacredit_repayment_ocb_customer FOREIGN KEY (ocb_customer_id)
    REFERENCES                silver.[ocb_customer](ocb_customer_id)
    );
GO

/*========================================================================================================================*

    19. SILVER DEPLOYMENT VERIFICATION

    Expected:

        1   load_batch
        5   reference
        2   OCB customer resolution
        3   Ananse
        3   SikaCredit
        2   Oman Remit

        TOTAL = 16

*========================================================================================================================*/
DECLARE @expected_silver_table_count INT = 16;

SELECT
    @expected_silver_table_count AS expected_silver_table_count,
    COUNT(*)                     AS actual_silver_table_count,
    CASE 
        WHEN COUNT(*) = @expected_silver_table_count
            THEN 'PASS'
        ELSE 'FAIL'
        END AS validation_status
FROM sys.tables AS t
INNER JOIN sys.schemas AS s ON
        t.SCHEMA_ID = s.SCHEMA_ID
WHERE s.name = 'silver';
GO

/*========================================================================================================================*

    20. FOREIGN KEY DEPLOYMENT VERIFICATION

    Expected:

        16 foreign keys

    Breakdown:

        OCB customer identity                  1
        Ananse customer                       1
        SikaCredit customer                   1
        Oman Remit customer                   1
        Ananse wallet                         2
        SikaCredit loan                       2
        Oman Remit remittance                 3
        Ananse transaction                    3
        SikaCredit repayment                  2

        TOTAL                                16

*========================================================================================================================*/
DECLARE @expected_silver_foreign_key_count INT = 16;

SELECT
    @expected_silver_foreign_key_count AS expected_silver_foreign_key_count,
    COUNT(*)                           AS actual_silver_foreign_key_count,
    CASE 
        WHEN COUNT(*) = @expected_silver_foreign_key_count
            THEN 'PASS'
        ELSE 'FAIL'
        END AS validation_status
FROM sys.foreign_keys AS fk
INNER JOIN sys.tables AS t ON
        fk.parent_object_id = t.OBJECT_ID
INNER JOIN sys.schemas AS s ON
        t.SCHEMA_ID = s.SCHEMA_ID
WHERE s.name = 'silver';
GO

/*========================================================================================================================*

    21. DISPLAY DEPLOYED SILVER TABLES

*========================================================================================================================*/
SELECT
    s.name AS SCHEMA_NAME,
    t.name AS table_name
FROM sys.tables AS t
INNER JOIN sys.schemas AS s ON
        t.SCHEMA_ID = s.SCHEMA_ID
WHERE s.name = 'silver'
ORDER BY t.name;
GO

/*========================================================================================================================*

    22. DISPLAY PRIMARY KEYS

*========================================================================================================================*/
SELECT
    s.name AS SCHEMA_NAME,
    t.name AS table_name,
    i.name AS primary_key_name
FROM sys.indexes AS i
INNER JOIN sys.tables AS t ON
        i.OBJECT_ID = t.OBJECT_ID
INNER JOIN sys.schemas AS s ON
        t.SCHEMA_ID = s.SCHEMA_ID
WHERE s.name = 'silver'
        AND i.is_primary_key = 1
ORDER BY t.name;
GO

/*========================================================================================================================*

    23. DISPLAY FOREIGN KEYS

*========================================================================================================================*/
SELECT
    fk.name                                 AS foreign_key_name,
    SCHEMA_NAME(parent_table.SCHEMA_ID)     AS child_schema,
    parent_table.name                       AS child_table,
    parent_column.name                      AS child_column,
    SCHEMA_NAME(referenced_table.SCHEMA_ID) AS parent_schema,
    referenced_table.name                   AS parent_table,
    referenced_column.name                  AS parent_column
FROM sys.foreign_keys AS fk
INNER JOIN sys.foreign_key_columns AS fkc ON
        fk.OBJECT_ID = fkc.constraint_object_id
INNER JOIN sys.tables AS parent_table ON
        fk.parent_object_id = parent_table.OBJECT_ID
INNER JOIN sys.columns AS parent_column ON
        parent_column.OBJECT_ID = fkc.parent_object_id
            AND parent_column.column_id = fkc.parent_column_id
INNER JOIN sys.tables AS referenced_table ON
        fk.referenced_object_id = referenced_table.OBJECT_ID
INNER JOIN sys.columns AS referenced_column ON
        referenced_column.OBJECT_ID = fkc.referenced_object_id
            AND referenced_column.column_id = fkc.referenced_column_id
WHERE SCHEMA_NAME(parent_table.SCHEMA_ID) = 'silver'
ORDER BY child_table,
    foreign_key_name;
GO

/*========================================================================================================================*

    24. FINAL SILVER DEPLOYMENT STATUS

*========================================================================================================================*/
DECLARE @actual_silver_table_count INT;
DECLARE @actual_silver_foreign_key_count INT;

SELECT
    @actual_silver_table_count = COUNT(*)
FROM sys.tables AS t
INNER JOIN sys.schemas AS s ON
        t.SCHEMA_ID = s.SCHEMA_ID
WHERE s.name = 'silver';

SELECT
    @actual_silver_foreign_key_count = COUNT(*)
FROM sys.foreign_keys AS fk
INNER JOIN sys.tables AS t ON
        fk.parent_object_id = t.OBJECT_ID
INNER JOIN sys.schemas AS s ON
        t.SCHEMA_ID = s.SCHEMA_ID
WHERE s.name = 'silver';

SELECT
    16                               AS expected_table_count,
    @actual_silver_table_count       AS actual_table_count,
    16                               AS expected_foreign_key_count,
    @actual_silver_foreign_key_count AS actual_foreign_key_count,
    CASE 
        WHEN @actual_silver_table_count = 16
                AND @actual_silver_foreign_key_count = 16
            THEN 'PASS'
        ELSE 'FAIL'
        END AS deployment_status;
GO

PRINT '===============================================================';
PRINT '>>> SILVER SOURCE-LAYER DEPLOYMENT COMPLETE <<<';
PRINT '===============================================================';
GO


